config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "static_pages#home"

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/under_construction', to: 'static_pages#under_construction'
  post    'friendships/friendrequest', controller: 'friendships', action: :edit

  resources :users, only: [:show, :new, :create, :edit, :show, :index] do
    resources :posts
    resources :friendships, only: [:index]
    member do
      get :liked_posts
      get :profile
    end
  end
  resources :posts do
    resources :comments
    member do
      get :liked_by_user
    end
  end

  resources :likes,  only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :notifications
  

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships 
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :notifications
  
  has_many :sent_notifications, class_name: "Notification", foreign_key: "notify_from_id"
  has_many :recieved_notifications, class_name: "Notification", foreign_key: "notify_id"
  
  has_many :notify_from, through: :notifications, source: :notify_from
  has_many :notify, through: :notifications, source: :notify
  
  has_many :likes, foreign_key: "liked_by_user_id"
  has_many :liked_posts, through: :likes, source: :liked_by_user
  has_many :posts, foreign_key: "author_id"
  has_many :comments, foreign_key: "author_id"
  

      def feed
        #inverse_friends = "SELECT user_id FROM friendships
                          #  WHERE user_id = user_id"

        friendships = Friendship.where('user_id =? OR friend_id=?', self.id, self.id)
        friends = friendships.collect { |x| x.user_id}
        
        Post.where("author_id = ? OR author_id IN (?)", self.id, friends)
      end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.all.paginate(page: params[:page])
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def edit
    end
    
    def profile
        @user = User.find(params[:id])
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    
        # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
    end
end

app/views/users/_user.html.erb
<li id="user">
    <% fullname = "#{user.first_name} #{user.last_name}" %>
    <%#= link_to gravatar_for(mini_post.author, size: 50), mini_post.user %>
    <span class="user"><%= link_to "#{fullname}'s Posts", user_posts_path(user) %><br></span>
    <span class="content">
        <%= pluralize(user.posts.count, "post") %>
        <%#= image_tag mini_post.picture.url if mini_post.picture? %>
    </span>
    <span class="timestamp">
        Joined <%= time_ago_in_words(user.created_at) %> ago.
        <% if current_user == (user) %>
            <%= link_to "delete account", user, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </span>
    <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post, :class => "btn btn-primary" %>
</li>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>

<div class="none">
    <ol class="users">
        <% if @users.any? %>
            <% @users.each do |user| %>
                <li><%= link_to "Profile", profile_user_path(user)%><%= render partial: 'users/user', locals: {user: user} %></li>
            <% end %>
            <%= will_paginate @users %>
        <% end %>
    </ol>
</div>

app/views/users/profile.html.erb
<div class="container">
      <div class="row">
      <div class="col-md-5  toppad  pull-right col-md-offset-3 ">
           <A href="edit.html" >Edit Profile</A>

        <A href="edit.html" >Logout</A>
       <br>
<p class=" text-info">May 05,2014,03:00 pm </p>
      </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
   
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @user.first_name %> <%=@user.last_name %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="" class="img-circle img-responsive"> </div>

                <div class=" col-md-9 col-lg-9 "> 
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Friends:</td>
                        <td><%= @user.friendships.count %></td>
                      </tr>
                      <tr>
                        <td>User since:</td>
                        <td><%= @user.created_at %></td>
                      </tr>
                      <tr>
                        <td>Date of Birth</td>
                        <td>01/24/1988</td>
                      </tr>
                     
                    </tbody>
                  </table>
                  <% unless  current_user.friends.include?(@user) %>
                      <%= render partial: 'users/user', :locals => {user: @user} %>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<h1>User</h1>


<ul class="users">
    <%= link_to "#{@user.first_name} #{@user.last_name}'s Posts", user_posts_path(@user) %>
</ul>

<h2>Friends</h2>
<ul>
  <% @user.friendships.each do |friendship| %>
    <li>
      <%= friendship.friend.first_name %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>

<h2>Friended by Users</h2>
<ul>
  <% @user.inverse_friends.each do |friend| %>
    <li><%= friend.first_name %></li>
  <% end %>
</ul>