config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "static_pages#home"

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/under_construction', to: 'static_pages#under_construction'
  post    'friendships/friendrequest', controller: 'friendships', action: :edit

  resources :users, only: [:show, :new, :create, :edit, :show, :index] do
    resources :posts
    resources :friendships, only: [:index]
    member do
      get :liked_posts
      get :profile
    end
  end
  resources :posts do
    resources :comments
    member do
      get :liked_by_user
    end
  end

  resources :likes,  only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :notifications
  

  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments
  
  has_many :likes, foreign_key: "liked_post_id"
  has_many :liked_by_users, :through => :likes, :source => :user
  validates :content, presence: true, length: { maximum: 500}
  
  
  def liked_by_user?(user)
    self.likes.any? {|x| x.liked_by_user_id == user.id }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def new
        @user = current_user
        @post = Post.new
    end
    
    def create
        @user = current_user
        @post = @user.posts.create!(post_params)
        flash[:sucess] = "Post created!"
        redirect_to user_post_path(@user, @post)
    end
    
    def show
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
    end
    
    def index
        @user = User.find(params[:user_id])
        @posts = @user.posts.all.paginate(page: params[:page])
    end
    
    
    private
        def post_params
           params.require(:post).permit(:content) 
        end
end 

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_like.html.erb
<%= form_for(current_user.likes.build, remote: true) do |f| %>
    <div><%= hidden_field_tag :liked_post_id, @post.id %></div>
    <%= f.submit "like", class:"btn btn-primary" %>
<% end %>

<%#, remote: true %>

app/views/posts/_like_form.html.erb
<div id="follow_form">
    <% if @post.liked_by_user?(current_user) %>
        <%= render 'unlike' %>
    <% else %>
        <%= render 'like' %>
    <% end %>
</div>

app/views/posts/_mini_post.html.erb
<li id="miniposts">
    <%#= link_to gravatar_for(mini_post.author, size: 50), mini_post.user %>
    <span class="user"><%= link_to "By #{mini_post.author.first_name}", mini_post.author %><br>
    <%= link_to "Post", user_post_path(mini_post.author, mini_post) %></span>
    <span class="content">
        <%= mini_post.content %><br>
        <%= pluralize(mini_post.likes.count, 'like') %>
    </span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(mini_post.created_at) %> ago.
        <% if current_user == (mini_post.author) %>
            <%= link_to "delete", mini_post, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

app/views/posts/_post.html.erb
<li id="minipost-<%= post.id %>">
    <%= link_to gravatar_for(post.author, size: 50), post.author %>
    <span class="user"><%= link_to post.author.first_name, post.author %></span>
    <span class="content">
        <%= post.content %>
        <%#= image_tag post.picture.url if post.picture? %>
    </span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(post.created_at) %> ago.
        <% if current_user == (post.author) %>
            <%= link_to "delete", post, method: :delete, data: { confirm: "You sure?" } %>
        <% end %>
    </span>
</li>

app/views/posts/_unlike.html.erb
<%= form_for(current_user.likes.find_by(liked_post_id: @post.id), 
                                html: {method: :delete}, remote: true) do |f| %>
    <%= f.submit "Unlike", class: "fa fa-reply" %>
<% end %>

<%#, remote: true %>

app/views/posts/index.html.erb
<% fullname = "#{@user.first_name}" + " #{@user.last_name}" %>
<% provide(:title, "All Posts for #{fullname}") %>
<h1>All Posts for <%= fullname %>:</h1>

<div class="none">
    <ol class="miniposts">
        <% if @posts.any? %>
            <% @posts.each do |user_post| %>
                <li><%= render partial: 'posts/mini_post', locals: {mini_post: user_post} %></li>
            <% end %>
            <%= will_paginate @posts %>
        <% end %>
    </ol>
</div>

<%= link_to "New Post", new_user_post_path(@user) %><br>


      

app/views/posts/new.html.erb
<% fullname = "#{current_user.first_name}" + " #{current_user.last_name}" %>
<% provide(:title, "New Post for #{fullname}") %>
<h1>New Post for <%= fullname %>:</h1>


<%= form_for @post do |f| %>
    <%= f.label :content %>
    <%= f.text_area :content %>
    
    <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
        <section class="comment-list">
            <article class="row">
                <div class="col-md-2 col-sm-2 hidden-xs">
                  <figure class="thumbnail">
                    <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                    <figcaption class="text-center"><%= @post.author.first_name %></figcaption>
                  </figure>
                </div>
                <div class="col-md-10 col-sm-10">
                  <div class="panel panel-default arrow left">
                    <div class="panel-body">
                      <header class="text-left">
                        <time class="comment-date" datetime="#{comment.created_at}"><i class="fa fa-clock-o"></i> <%= @post.created_at %></time>
                      </header>
                      <div class="comment-post">
                        <p><%= @post.content %></p>
                      </div>
                      <div id="like_form">
                       <p class="text-right"> <%= render 'posts/like_form' %></p>
                      </div>
                      <%#= <a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a> %>
                    </div>
                  </div>
                </div>
              </article>
            </section>
        </div>
    </div>
  <div class="row">
    <div class="col-md-8">
      <h2 class="page-header">Comments</h2>
        <section class="comment-list">
            <% if @post.comments.any? %>
                <% @post.comments.each do |comment| %>
                    <article class="row">
                        <div class="col-md-2 col-sm-2 hidden-xs">
                          <figure class="thumbnail">
                            <img class="img-responsive" src="http://www.keita-gaming.com/assets/profile/default-avatar-c5d8ec086224cb6fc4e395f4ba3018c2.jpg" />
                            <figcaption class="text-center"><%= comment.author.first_name %></figcaption>
                          </figure>
                        </div>
                        <div class="col-md-10 col-sm-10">
                          <div class="panel panel-default arrow left">
                            <div class="panel-body">
                              <header class="text-left">
                                <time class="comment-date" datetime="#{comment.created_at}"><i class="fa fa-clock-o"></i> <%= comment.created_at %></time>
                              </header>
                              <div class="comment-post">
                                <p><%= comment.content %></p>
                              </div>
                              <%#= <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p> %>
                            </div>
                          </div>
                        </div>
                      </article>
                    <% end %>
                <% end %>
                <%= render 'comments/form', locals: {post: @post} %>
            </section>
        </div>
    </div>
</div>