config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "static_pages#home"

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'

  get    '/under_construction', to: 'static_pages#under_construction'
  post    'friendships/friendrequest', controller: 'friendships', action: :edit

  resources :users, only: [:show, :new, :create, :edit, :show, :index] do
    resources :posts
    resources :friendships, only: [:index]
    member do
      get :liked_posts
      get :profile
    end
  end
  resources :posts do
    resources :comments
    member do
      get :liked_by_user
    end
  end

  resources :likes,  only: [:create, :destroy]
  resources :friendships, only: [:create, :update, :destroy]
  resources :notifications
  

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "User"
  belongs_to :post
  has_many :notifications, as: :notifyable
  validates :content, presence: true, length: { maximum: 150}
end

app/models/friendship.rb
class Friendship < ApplicationRecord
    belongs_to :user
    belongs_to :friend, :class_name => "User"
    has_one :notification, as: :notifyable
    validate :disallow_self_referential_friendship

    def disallow_self_referential_friendship
        if friend_id == user_id
          errors.add(:friend_id, 'cannot refer back to the author')
        end
      end
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :liked_by_user, class_name: "User"
    belongs_to :liked_post, class_name: "Post"
    has_one :notification, as: :notifyable
end

app/models/notification.rb
class Notification < ApplicationRecord
    belongs_to :notifyable, :polymorphic => true
    
    belongs_to :notify_from, class_name: "User"
    
    belongs_to :notify, class_name: "User"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments
  
  has_many :likes, foreign_key: "liked_post_id"
  has_many :liked_by_users, :through => :likes, :source => :user
  validates :content, presence: true, length: { maximum: 500}
  
  
  def liked_by_user?(user)
    self.likes.any? {|x| x.liked_by_user_id == user.id }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friendships 
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :notifications
  
  has_many :sent_notifications, class_name: "Notification", foreign_key: "notify_from_id"
  has_many :recieved_notifications, class_name: "Notification", foreign_key: "notify_id"
  
  has_many :notify_from, through: :notifications, source: :notify_from
  has_many :notify, through: :notifications, source: :notify
  
  has_many :likes, foreign_key: "liked_by_user_id"
  has_many :liked_posts, through: :likes, source: :liked_by_user
  has_many :posts, foreign_key: "author_id"
  has_many :comments, foreign_key: "author_id"
  

      def feed
        #inverse_friends = "SELECT user_id FROM friendships
                          #  WHERE user_id = user_id"

        friendships = Friendship.where('user_id =? OR friend_id=?', self.id, self.id)
        friends = friendships.collect { |x| x.user_id}
        
        Post.where("author_id = ? OR author_id IN (?)", self.id, friends)
      end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :store_action
  
  def store_action
    return unless request.get? 
    if (request.path != "/users/sign_in" &&
        request.path != "/users/sign_up" &&
        request.path != "/users/password/new" &&
        request.path != "/users/password/edit" &&
        request.path != "/users/confirmation" &&
        request.path != "/users/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:user, request.fullpath)
    end
  end
  
  protected
  
    def authenticate_user!
      if user_signed_in?
        super
      else
        redirect_to root_path
      end
    end
    
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:post, keys: [:content])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def new
        @comment = Comment.new
    end
    
    def create
        @post = Post.find(params[:post_id])
        @user = User.find(@post.author_id)
        @comment = @post.comments.new(comment_params.merge(author: current_user))
        if @comment.save
            redirect_to user_post_path(@user, @post)
        else
            @comment.destroy
            flash[:warning] = flash_error_message(@comment)
            redirect_to user_post_path(@user, @post)
        end
    end
    
    
    def flash_error_message(arg)
        "The form contains #{arg.errors.count} error: #{arg.errors.full_messages.join(', ')}"       
    end
    
    private
        def comment_params
           params.require(:comment).permit(:content)
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def create
        @post= Post.find(params[:liked_post_id])
        @like = current_user.likes.create!(liked_post_id: @post.id)
        @like.notifications.create!(notify_from_id: current_user.id, notify_id: @post.author.id)
        respond_to do |format|
            format.html { redirect_to user_post_path(@post.author, @post) }
            format.js
        end
    end
    
    def destroy
        @like = Like.find(params[:id])
        @user = @like.liked_by_user
        @post = @like.liked_post
        @like.destroy
        respond_to do |format|
            format.html { redirect_to user_post_path(@post.author, @post) }
            format.js
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def new
        @user = current_user
        @post = Post.new
    end
    
    def create
        @user = current_user
        @post = @user.posts.create!(post_params)
        flash[:sucess] = "Post created!"
        redirect_to user_post_path(@user, @post)
    end
    
    def show
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
    end
    
    def index
        @user = User.find(params[:user_id])
        @posts = @user.posts.all.paginate(page: params[:page])
    end
    
    
    private
        def post_params
           params.require(:post).permit(:content) 
        end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.all.paginate(page: params[:page])
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def edit
    end
    
    def profile
        @user = User.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
        
    #Returns the full title on a per-page basis
    def full_title(page_title = '')
        base_title = "Odin Facebook"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
        # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Help", help_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Odin Facebook", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Users", users_path %></li>
              <li><%= link_to "Profile", profile_user_path(current_user) %></li>
              <li><%= link_to "Settings", under_construction_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Notifications <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if current_user.recieved_notifications.any? %>
                    <% current_user.recieved_notifications.each do|notification| %>
                      <li><%= link_to "#{notification.notifyable_type}", notification_path(notification) %></li>
                    <% end %>
                  <% else %>
                    <li> No Notifications</li>
                  <% end %>
                </ul>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
              </li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="miniposts">
        <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>